### ISSUE TITLE
read_bam_file.d fails on dmd 2.066.1 

### ISSUE THREAD

**Issue by georgeG** [biod/BioD#12]
On running example1.d (Mac OS X 10.10, dmd 2.066.1
```
rdmd -I.. read_bam_file.d
```
fails with this error message 

```
Undefined symbols for architecture x86_64:
  "_D3bio3bam4read41__T12EagerBamReadTS3bio3bam4read7BamReadZ12EagerBamRead11__xopEqualsFKxS3bio3bam4read41__T12EagerBamReadTS3bio3bam4read7BamReadZ12EagerBamReadKxS3bio3bam4read41__T12EagerBamReadTS3bio3bam4read7BamReadZ12EagerBamReadZb", referenced from:
      _D80TypeInfo_S3bio3bam4read41__T12EagerBamReadTS3bio3bam4read7BamReadZ12EagerBamRead6__initZ in read_bam_file.o
  "_D3bio3bam4read41__T12EagerBamReadTS3bio3bam4read7BamReadZ12EagerBamRead9__xtoHashFNbNeKxS3bio3bam4read41__T12EagerBamReadTS3bio3bam4read7BamReadZ12EagerBamReadZm", referenced from:
      _D80TypeInfo_S3bio3bam4read41__T12EagerBamReadTS3bio3bam4read7BamReadZ12EagerBamRead6__initZ in read_bam_file.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
--- errorlevel 1 `
```

**Comment by lomereiter** [comment]
I'd be grateful if someone shown me a way to fix this.
Two months ago I created a [thread](http://forum.dlang.org/thread/rqnazthmemadbbwsfqlx@forum.dlang.org) on dlang forums to no avail :(

So the only advice I can give is to compile with LDC or an older version of DMD.

**Comment by georgeG** [comment]
Thank you for pointing to the thread. I had not seen it. hopefully it will be fixed and I see it has more to do with DMD than the actual code.

**Comment by biorelated** [comment]
Compile error with `DMD64 D Compiler v2.067.1`

`../bio/bam/md/operation.d(19): Error: struct bio.bam.md.operation.MdOperation destructors, postblits and invariants are not allowed in overlapping fields _match and _mismatch
/usr/share/dmd/src/phobos/std/traits.d(832): Error: forward reference to inferred return type of function call 'mdOperations'
../bio/bam/md/parse.d(146):        while looking for match for ReturnType!(mdOperations)
../bio/bam/reference.d(78): Error: need 'this' for '_ref_id' of type 'int'
../bio/bam/reference.d(79): Error: need 'this' for '_ref_id' of type 'int'
Failed: ["dmd", "-I..", "-v", "-o-", "read_bam_file.d", "-I."]`

**Comment by SmithRyan** [comment]
Glad to see this isn't unique. For those who do not have this problem with DMD- what version are you using?

**Comment by biorelated** [comment]
LDC

**Comment by lomereiter** [comment]
For 2.067, I managed to get past the compilation errors (by removing the invariant at the bottom of `bio/core/tinymap.d` and moving `private:` declarations to the top of `bio.bam.reference.ReferenceSequence` class) but I'm still getting the same linking errors as in 2.066.
Unfortunately, this means that the DMD backend is buggy as hell. Please use LDC, it seems to be much more stable.

**Comment by biorelated** [comment]
Will you push the changes you made to the repo? Maybe consider filing the linking errors as a bug report with DMD.  It would be nice to be able to compile and link with the latest DMD compiler. :)

**Comment by lomereiter** [comment]
I pushed the changes, but filing such bug report is unlikely to help, I should try to reduce the test case first.

**Comment by biorelated** [comment]
After the couple of the new commits the read_bam_file example now compiles on DMD64 D Compiler v2.067.1. You could close this issue now.

**Comment by lomereiter** [comment]
I checked, and it still doesn't compile, with 2.068-rc1 as well. Perhaps you first compiled it with `--compiler=ldmd2`, and then again with `--compiler=dmd` without using `--force` flag?

**Comment by biorelated** [comment]
Maybe should advice to drop DMD 2.066. I am not sure if someone will want to use it, given that ldc offers better compilation and error messages. As I get more conversant with the D internals maybe I will try to get to the bottom of it but I have no timeline. :)

**Comment by lomereiter** [comment]
After a bit of trial and error I accidentally discovered that DMD doesn't compile a single `static assert` in `bio.bam.pileup` module, so I simply commented it out as it doesn't matter that much. Yay!

**Comment by biorelated** [comment]
Yay!
